### ISSUE TITLE
Random Tetrominos

### ISSUE THREAD

**Issue by tosh** [djblue/tetris#2]
If I understand correctly you are drawing a random tetromino piece at a time

https://github.com/djblue/tetris/blob/360d13283ba212c7bdc90d14083086778eaec1ef/src/tetris/core.cljs#L157

Many Tetris implementations use a bag to make sure pieces appear in a more predictable way. Makes the game a bit more fun imho.

https://tetris.fandom.com/wiki/Random_Generator

You might already have come across this but just wanted to bring it to your attention in case you haven't.

**Comment by djblue** [comment]
I wasn't aware. Thanks for the information. This would definitely make the game way better. I've gotten 3 `I` tetrominos in row and then not again for a while way too many times! :laughing:

**Comment by tosh** [comment]
Same here 😅

thanks for releasing the source, pleasure to read

**Comment by djblue** [comment]
Thanks for the kind words. Does https://github.com/djblue/tetris/commit/2165c6f96bbbd7f55489db4b79cc2b8c21ea45d3 look about right?

**Comment by tosh** [comment]
looks good to me @ bag
